# Generated by Django 4.2.3 on 2023-07-24 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Minapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(error_messages={'required': 'Обязательное поле', 'unique': 'Ведомство с таким названием уже существует'}, max_length=255, unique=True, verbose_name='Название'),
        ),
    ]
