# Generated by Django 4.2.3 on 2023-09-12 08:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Minapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Конец'),
        ),
        migrations.AddField(
            model_name='event',
            name='group_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Minapp.group', verbose_name='Группа'),
        ),
        migrations.AddField(
            model_name='event',
            name='start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Начало '),
        ),
        migrations.AlterField(
            model_name='event',
            name='datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата/время'),
        ),
        migrations.AlterField(
            model_name='event',
            name='recipient_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Получатель'),
        ),
    ]
