# Generated by Django 4.2.3 on 2023-08-23 12:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Minapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 23, 15, 55, 56, 377883), verbose_name='Дата/время'),
        ),
    ]
