# Generated by Django 4.2.3 on 2023-09-24 09:12

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Minapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='photo',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(verbose_name='Фотография'), blank=True, null=True, size=None),
        ),
    ]
