# Generated by Django 4.2.3 on 2023-10-02 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Minapp', '0002_alter_event_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
