# Generated by Django 4.2.3 on 2023-07-25 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Minapp', '0002_location_is_active_alter_location_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Эл. почта'),
        ),
    ]
