# Generated by Django 4.2.3 on 2023-10-02 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Minapp', '0003_remove_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(unique=True, verbose_name='Телефон'),
        ),
    ]
