# Generated by Django 4.2.3 on 2023-07-25 13:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Minapp', '0003_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 25, 16, 2, 51, 863748), verbose_name='Дата/время'),
        ),
    ]
