# Generated by Django 4.2.3 on 2023-10-03 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Minapp', '0005_alter_user_phone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['id'], 'verbose_name_plural': 'Пользователи'},
        ),
    ]
