# Generated by Django 4.2.3 on 2023-08-21 13:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Minapp', '0007_alter_event_datetime_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 21, 16, 27, 30, 101387), verbose_name='Дата/время'),
        ),
    ]
