# Generated by Django 4.2.3 on 2023-08-22 12:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Minapp', '0013_alter_event_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 22, 15, 9, 26, 101477), verbose_name='Дата/время'),
        ),
    ]
